### PR TITLE
Change suggested text editor

### LINKED ISSUE #8: Suggestion for default text editor
I volunteered to mentor for the upcoming HTML/CSS workshop in June, and was just going over the slides to be prepared. 

For suggested text editor, it says Sublime as the default, or for Mac users suggests Atom or Windows users Notepad++.

Atom works pretty well on Windows now, so it could be the default choice for everyone. Some advantages over Sublime are:
* free (with no purchase popup every so many saves)
* easier to use plugin manager
* similar keyboard shortcuts to Sublime, so those coming from Sublime will feel instantly comfortable in Atom

If you think it's a good idea to switch to Atom, I could submit a PR for changing that slide (haven't used RevealJS before but seems fairly straightforward).

### PR DESCRIPTION
**Pull request by danielabar**
Fixes #8 

Change slide about text editors. 

Upon noticing major whitespace changes from a simple 3 line change, introduced editorconfig. Also added contributing section in Readme, including Atom "quirk" with Whitespace plugin. (some irony in recommending Atom while at the same time discovering quirks)

### CODE REVIEW

**Comment by christinatruong** [comment]
Ha yes, just a tad ironic.  It might be a little while before I merge this request but thanks again for making this update!

**Comment by danielabar** [comment]
np, it was fun learning something new about Atom :-)

**Comment by christinatruong** [comment]
Finally updated these slides! I didn't merge your changes since there were so many updates but I did manually add in your updates. Thanks so much!

**Comment by danielabar** [comment]
Awesome, thanks.

**Pull request closed without merging**
